/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import Conexao.DAOCanal;
import Conexao.DAOUsuario;
import Modelo.Usuario;
import java.awt.Dimension;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author 70670989630
 */
public class FormPrincipal extends javax.swing.JFrame {
    DAOUsuario dao = new DAOUsuario();
    static Usuario usuarioLogado = null;
    /**
     * Creates new form Main
     */
    public FormPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    private void sair() {
        usuarioLogado = null;
        menuUsuario.setVisible(true);
        menuEntrar.setVisible(true);
        menuParceria.setVisible(true);
        menuCanal.setVisible(false);
        menuVideo.setVisible(false);
        menuSair.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelGeral = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        menuUsuario = new javax.swing.JMenuItem();
        menuEntrar = new javax.swing.JMenuItem();
        menuParceria = new javax.swing.JMenuItem();
        menuCanal = new javax.swing.JMenuItem();
        menuVideo = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();
        menuAjuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Projeto_Videos");

        javax.swing.GroupLayout painelGeralLayout = new javax.swing.GroupLayout(painelGeral);
        painelGeral.setLayout(painelGeralLayout);
        painelGeralLayout.setHorizontalGroup(
            painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 615, Short.MAX_VALUE)
        );
        painelGeralLayout.setVerticalGroup(
            painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 329, Short.MAX_VALUE)
        );

        menuCadastro.setText("Cadastros");

        menuUsuario.setText("Novo Usuário");
        menuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuarioActionPerformed(evt);
            }
        });
        menuCadastro.add(menuUsuario);

        menuEntrar.setText("Entrar");
        menuEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEntrarActionPerformed(evt);
            }
        });
        menuCadastro.add(menuEntrar);

        menuParceria.setText("Nova Parceria");
        menuParceria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuParceriaActionPerformed(evt);
            }
        });
        menuCadastro.add(menuParceria);

        menuCanal.setText("Novo Canal");
        menuCanal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCanalActionPerformed(evt);
            }
        });
        menuCanal.setVisible(false);
        menuCadastro.add(menuCanal);

        menuVideo.setText("Novo vídeo");
        menuVideo.setVisible(false);
        menuVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVideoActionPerformed(evt);
            }
        });
        menuCadastro.add(menuVideo);

        jMenuBar1.add(menuCadastro);

        menuSair.setText("Sair");
        menuSair.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                menuSairMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        menuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSairMouseClicked(evt);
            }
        });
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        menuSair.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                menuSairKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                menuSairKeyTyped(evt);
            }
        });

        menuSair.setVisible(false);

        jMenuBar1.add(menuSair);

        menuAjuda.setText("Ajuda");
        jMenuBar1.add(menuAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuarioActionPerformed
        // TODO add your handling code here:
        CadastroUsuario cadUser = new CadastroUsuario(this, true);
        cadUser.setVisible(true);
        cadUser.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        cadUser.setResizable(false);
        cadUser.setLocationRelativeTo(null);
        cadUser.setResizable(false);
    }//GEN-LAST:event_menuUsuarioActionPerformed

    private void menuEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEntrarActionPerformed
        Login logIn = new Login(this, true);
        logIn.setLocationRelativeTo(null);
        logIn.setResizable(false);
        logIn.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        logIn.setVisible(true);
        System.out.println(usuarioLogado.getCodUsuario());
        if(usuarioLogado != null) {
            menuUsuario.setVisible(false);
            menuEntrar.setVisible(false);
            menuParceria.setVisible(false);
            menuCanal.setVisible(true);
            menuVideo.setVisible(true);
            menuSair.setVisible(true);
        }
    }//GEN-LAST:event_menuEntrarActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        
    }//GEN-LAST:event_menuSairActionPerformed

    private void menuCanalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCanalActionPerformed
        FormCanal fmCanal = new FormCanal(this, true);
        fmCanal.setLocationRelativeTo(null);
        fmCanal.setResizable(false);
        fmCanal.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        fmCanal.setVisible(true);
    }//GEN-LAST:event_menuCanalActionPerformed

    private void menuSairKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_menuSairKeyPressed
        
    }//GEN-LAST:event_menuSairKeyPressed

    private void menuSairKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_menuSairKeyTyped
        
    }//GEN-LAST:event_menuSairKeyTyped

    private void menuSairMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_menuSairMenuKeyPressed

    }//GEN-LAST:event_menuSairMenuKeyPressed

    private void menuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSairMouseClicked
        int opcao = JOptionPane.showOptionDialog(null, "Deseja realmente sair?", "Pergunta", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,
                null, new String[] {"Sim", "Não"}, "Sim");
        
        if(opcao == 0) {
            sair();
        }
    }//GEN-LAST:event_menuSairMouseClicked

    private void menuVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVideoActionPerformed
        FormVideo fv = new FormVideo(this, true);
        fv.setLocationRelativeTo(null);
        fv.setResizable(false);
        fv.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        fv.setVisible(true);
    }//GEN-LAST:event_menuVideoActionPerformed

    private void menuParceriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuParceriaActionPerformed
        FormParceria fp = new FormParceria(this, true);
        fp.setLocationRelativeTo(null);
        fp.setResizable(false);
        fp.setVisible(true);
        fp.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_menuParceriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenuItem menuCanal;
    private javax.swing.JMenuItem menuEntrar;
    private javax.swing.JMenuItem menuParceria;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenuItem menuUsuario;
    private javax.swing.JMenuItem menuVideo;
    private javax.swing.JPanel painelGeral;
    // End of variables declaration//GEN-END:variables

}
