/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package visual;

import Conexao.DAOCanal;
import Conexao.DAOParcerias;
import Modelo.Canal;
import Modelo.ConverteData;
import Modelo.ConverteDataWEB;
import Modelo.Parceria;
import java.util.ArrayList;
import java.util.Comparator;
import javax.print.event.PrintJobEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author taiki-hamasaki
 */
public class FormParceria extends javax.swing.JDialog {
    DAOParcerias daoParcerias = new DAOParcerias();
    DAOCanal daoCanal = new DAOCanal();
    
    Parceria objParceria = new Parceria();
    
    ConverteDataWEB converteDataWeb = new ConverteDataWEB();
    /**
     * Creates new form FormParceria
     */
    public FormParceria(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        listCanal.clear();
        listCanal.addAll(daoCanal.getLista());
        listParceiros.clear();
        trataEdicao(false);
    }
    
    private void mudancas(int do_or_undo, Canal c) {
        if(do_or_undo == 0) {
            listCanal.remove(c);
            listParceiros.add(c);
        } else if(do_or_undo == 1) {
            listCanal.add(c);
            // Retorna para a lista de Canais disponiveis, ordenando de acordo com o getCodCanal()
            // na ordem que foi criado no bd
            listCanal.sort(Comparator.comparing(Canal::getCodCanal));
            listParceiros.remove(c);
        }
    }
    
    private void trataEdicao(boolean editando) {
        btnFinalizar.setEnabled(editando);
        btnCancelar.setEnabled(editando);
        jListCanais.setEnabled(editando);
        jListParceiros.setEnabled(editando);
        txtEmpresa.setEnabled(editando);
        txtDataInicio.setEnabled(editando);
        txtDataFim.setEnabled(editando);
        btnContratarParceria.setEnabled(editando);
        btnRemove.setEnabled(editando);
        if(editando) {
            txtEmpresa.setText("");
            listCanal.clear();
            listCanal.addAll(daoCanal.getLista());
            listParceiros.clear();
        }
    }
    
    private boolean validaCampos() {
        if(!(txtEmpresa.getText().length() >= 0)) {
            JOptionPane.showMessageDialog(null, "Informe o nome da empresa");
            return false;
        }
        
        if(!(jListParceiros.getSelectedIndex() >= 0)) {
            JOptionPane.showMessageDialog(null, "Informe o Canal parceiro");
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        listCanal = org.jdesktop.observablecollections.ObservableCollections.observableList(new ArrayList<Canal>());
        listParceiros = org.jdesktop.observablecollections.ObservableCollections.observableList(new ArrayList<Canal>());
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        javax.swing.text.MaskFormatter maskData = null;
        try{
            maskData = new javax.swing.text.MaskFormatter("##/##/####");
            maskData.setPlaceholderCharacter('_');
        }catch(Exception e){
            System.out.println("Erro na mascara "+e);
        }
        txtDataInicio = new javax.swing.JFormattedTextField(maskData);
        txtDataFim = new javax.swing.JFormattedTextField(maskData);
        jScrollPane1 = new javax.swing.JScrollPane();
        jListCanais = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListParceiros = new javax.swing.JList();
        btnContratarParceria = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnCadastrar = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nova Parceria");

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        lblTitulo.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Cadastre uma Parceria");
        jPanel1.add(lblTitulo);

        txtEmpresa.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        txtEmpresa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nome da Empresa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 1, 14))); // NOI18N

        txtDataInicio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Início do Contrato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 1, 14))); // NOI18N
        txtDataInicio.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N

        txtDataFim.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fim do Contrato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 1, 14))); // NOI18N
        txtDataFim.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Canais Disponíveis", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 1, 18))); // NOI18N

        org.jdesktop.swingbinding.JListBinding jListBinding = org.jdesktop.swingbinding.SwingBindings.createJListBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listCanal, jListCanais);
        bindingGroup.addBinding(jListBinding);

        jScrollPane1.setViewportView(jListCanais);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Parceiros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 1, 18))); // NOI18N

        jListBinding = org.jdesktop.swingbinding.SwingBindings.createJListBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listParceiros, jListParceiros);
        bindingGroup.addBinding(jListBinding);

        jScrollPane2.setViewportView(jListParceiros);

        btnContratarParceria.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        btnContratarParceria.setText("Contratar Parceiro");
        btnContratarParceria.setToolTipText("");
        btnContratarParceria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContratarParceriaActionPerformed(evt);
            }
        });

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        jPanel2.setLayout(new java.awt.GridLayout());

        btnCadastrar.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCadastrar);

        btnFinalizar.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });
        jPanel2.add(btnFinalizar);

        btnCancelar.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnContratarParceria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRemove))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                        .addComponent(txtDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130)
                        .addComponent(txtDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDataInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(btnContratarParceria)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemove)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContratarParceriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContratarParceriaActionPerformed
        if(!(jListCanais.getSelectedIndex() >= 0)) {
            JOptionPane.showMessageDialog(null, "Selecione um canal para parceiro");
            jListCanais.requestFocus();
        } else {
            int linhaSelecionada = jListCanais.getSelectedIndex();
            Canal c = listCanal.get(linhaSelecionada);
            mudancas(0, c);
        }
    }//GEN-LAST:event_btnContratarParceriaActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        if (!(jListParceiros.getSelectedIndex() >= 0)) {
            JOptionPane.showMessageDialog(null, "Nenhum canal a ser removido");
            jListParceiros.requestFocus();

        } else {
            int linhaSelecionada = jListParceiros.getSelectedIndex();
            Canal c = listParceiros.get(linhaSelecionada);
            mudancas(1, c);
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        listParceiros.clear();
        listCanal.clear();
        listCanal.addAll(daoCanal.getLista());
        trataEdicao(true);
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        if(validaCampos()) {
            objParceria.setNomeEmpresa(txtEmpresa.getText());
            objParceria.setInicioContrato(converteDataWeb.converteCalendario(txtDataInicio.getText()));
            objParceria.setFimContrato(converteDataWeb.converteCalendario(txtDataFim.getText()));
            objParceria.setCanalParceiro((Canal) jListParceiros.getSelectedValue());
            daoParcerias.incluir(objParceria);
            listParceiros.remove(jListParceiros.getSelectedIndex());
            mudancas(1, objParceria.getCanalParceiro());
            if(!(listParceiros.size() >= 0)) {
                trataEdicao(false);
            }
        }
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        trataEdicao(false);
        txtDataInicio.setText("");
        txtDataFim.setText("");
        listCanal.clear();
        listCanal.addAll(daoCanal.getLista());
        listParceiros.clear();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormParceria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormParceria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormParceria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormParceria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormParceria dialog = new FormParceria(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnContratarParceria;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnRemove;
    private javax.swing.JList jListCanais;
    private javax.swing.JList jListParceiros;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTitulo;
    private java.util.List<Canal> listCanal;
    private java.util.List<Canal> listParceiros;
    private javax.swing.JFormattedTextField txtDataFim;
    private javax.swing.JFormattedTextField txtDataInicio;
    private javax.swing.JTextField txtEmpresa;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
